# Generated by Django 3.2.18 on 2023-06-12 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='desti',
            new_name='dests',
        ),
    ]
