# Generated by Django 3.2.18 on 2023-06-12 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_rename_desti_comments_dests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='dests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myApp.destination'),
        ),
    ]
